In [2]:
import numpy as np
import pandas as pd

## OBJECT Creation

In [3]:
s = pd.Series([1,3,4,5,6,np.nan,8]) # Series by passing list
print(s)

0    1.0
1    3.0
2    4.0
3    5.0
4    6.0
5    NaN
6    8.0
dtype: float64


In [4]:
dates = pd.date_range("20220101",periods=6)
print(dates)

DatetimeIndex(['2022-01-01', '2022-01-02', '2022-01-03', '2022-01-04',
               '2022-01-05', '2022-01-06'],
              dtype='datetime64[ns]', freq='D')


In [5]:
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list("ABCD"))
print(df) # data frame

                   A         B         C         D
2022-01-01 -1.200152 -2.126619 -1.314353 -0.656879
2022-01-02 -0.570162  0.632777  1.306604 -0.959269
2022-01-03  0.410459  0.026635  1.061087 -0.906371
2022-01-04  0.857084  1.175681 -1.448692 -0.436976
2022-01-05 -0.222425 -1.417048 -2.063990  0.181362
2022-01-06  0.202408 -0.615880  0.388940 -0.651837


In [6]:
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)
print(df2)

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo


## Viewing Data

In [7]:
print(df.head()) # first few records

                   A         B         C         D
2022-01-01 -1.200152 -2.126619 -1.314353 -0.656879
2022-01-02 -0.570162  0.632777  1.306604 -0.959269
2022-01-03  0.410459  0.026635  1.061087 -0.906371
2022-01-04  0.857084  1.175681 -1.448692 -0.436976
2022-01-05 -0.222425 -1.417048 -2.063990  0.181362


In [8]:
print(df.tail()) # last few records

                   A         B         C         D
2022-01-02 -0.570162  0.632777  1.306604 -0.959269
2022-01-03  0.410459  0.026635  1.061087 -0.906371
2022-01-04  0.857084  1.175681 -1.448692 -0.436976
2022-01-05 -0.222425 -1.417048 -2.063990  0.181362
2022-01-06  0.202408 -0.615880  0.388940 -0.651837


In [9]:
print(df.index)
print(df.columns)

DatetimeIndex(['2022-01-01', '2022-01-02', '2022-01-03', '2022-01-04',
               '2022-01-05', '2022-01-06'],
              dtype='datetime64[ns]', freq='D')
Index(['A', 'B', 'C', 'D'], dtype='object')


In [10]:
print(df.to_numpy()) # will not include index and columns.

[[-1.20015181 -2.12661922 -1.31435285 -0.65687936]
 [-0.57016203  0.63277669  1.30660388 -0.95926855]
 [ 0.41045933  0.02663456  1.06108696 -0.90637111]
 [ 0.85708401  1.17568089 -1.44869173 -0.43697613]
 [-0.22242498 -1.41704813 -2.06399023  0.1813618 ]
 [ 0.20240764 -0.61588017  0.38893969 -0.65183728]]


In [11]:
print(df.describe()) # statistics of data

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.087131 -0.387409 -0.345067 -0.571662
std    0.736669  1.248413  1.439184  0.415005
min   -1.200152 -2.126619 -2.063990 -0.959269
25%   -0.483228 -1.216756 -1.415107 -0.843998
50%   -0.010009 -0.294623 -0.462707 -0.654358
75%    0.358446  0.481241  0.893050 -0.490691
max    0.857084  1.175681  1.306604  0.181362


In [12]:
print(df.T) # Transposing 

   2022-01-01  2022-01-02  2022-01-03  2022-01-04  2022-01-05  2022-01-06
A   -1.200152   -0.570162    0.410459    0.857084   -0.222425    0.202408
B   -2.126619    0.632777    0.026635    1.175681   -1.417048   -0.615880
C   -1.314353    1.306604    1.061087   -1.448692   -2.063990    0.388940
D   -0.656879   -0.959269   -0.906371   -0.436976    0.181362   -0.651837


## Sorting DF 

In [13]:
print(df.sort_index(axis=1, ascending=False))

                   D         C         B         A
2022-01-01 -0.656879 -1.314353 -2.126619 -1.200152
2022-01-02 -0.959269  1.306604  0.632777 -0.570162
2022-01-03 -0.906371  1.061087  0.026635  0.410459
2022-01-04 -0.436976 -1.448692  1.175681  0.857084
2022-01-05  0.181362 -2.063990 -1.417048 -0.222425
2022-01-06 -0.651837  0.388940 -0.615880  0.202408


In [14]:
print(df.sort_values(by="B"))

                   A         B         C         D
2022-01-01 -1.200152 -2.126619 -1.314353 -0.656879
2022-01-05 -0.222425 -1.417048 -2.063990  0.181362
2022-01-06  0.202408 -0.615880  0.388940 -0.651837
2022-01-03  0.410459  0.026635  1.061087 -0.906371
2022-01-02 -0.570162  0.632777  1.306604 -0.959269
2022-01-04  0.857084  1.175681 -1.448692 -0.436976


## Selection

In [15]:
print(df["A"])

2022-01-01   -1.200152
2022-01-02   -0.570162
2022-01-03    0.410459
2022-01-04    0.857084
2022-01-05   -0.222425
2022-01-06    0.202408
Freq: D, Name: A, dtype: float64


In [16]:
print(df[0:3])

                   A         B         C         D
2022-01-01 -1.200152 -2.126619 -1.314353 -0.656879
2022-01-02 -0.570162  0.632777  1.306604 -0.959269
2022-01-03  0.410459  0.026635  1.061087 -0.906371


In [17]:
print(df["20220102":"20220105"])

                   A         B         C         D
2022-01-02 -0.570162  0.632777  1.306604 -0.959269
2022-01-03  0.410459  0.026635  1.061087 -0.906371
2022-01-04  0.857084  1.175681 -1.448692 -0.436976
2022-01-05 -0.222425 -1.417048 -2.063990  0.181362


In [18]:
# By label
df.loc[dates[0]]

A   -1.200152
B   -2.126619
C   -1.314353
D   -0.656879
Name: 2022-01-01 00:00:00, dtype: float64

In [19]:
df.loc[:, ["A", "B"]] # By label

A         B
2022-01-01 -1.200152 -2.126619
2022-01-02 -0.570162  0.632777
2022-01-03  0.410459  0.026635
2022-01-04  0.857084  1.175681
2022-01-05 -0.222425 -1.417048
2022-01-06  0.202408 -0.615880

In [20]:
df.iloc[3] # by position

A    0.857084
B    1.175681
C   -1.448692
D   -0.436976
Name: 2022-01-04 00:00:00, dtype: float64

In [21]:
df.iloc[3:5, 0:2] # by position

A         B
2022-01-04  0.857084  1.175681
2022-01-05 -0.222425 -1.417048

## Boolean indexing

In [22]:
df[df["A"] > 0]

A         B         C         D
2022-01-03  0.410459  0.026635  1.061087 -0.906371
2022-01-04  0.857084  1.175681 -1.448692 -0.436976
2022-01-06  0.202408 -0.615880  0.388940 -0.651837

In [23]:
df[df > 0]

A         B         C         D
2022-01-01       NaN       NaN       NaN       NaN
2022-01-02       NaN  0.632777  1.306604       NaN
2022-01-03  0.410459  0.026635  1.061087       NaN
2022-01-04  0.857084  1.175681       NaN       NaN
2022-01-05       NaN       NaN       NaN  0.181362
2022-01-06  0.202408       NaN  0.388940       NaN

In [24]:
df2 = df.copy()
df2["E"] = ["one", "one", "two", "three", "four", "three"]
print(df2)
df2[df2["E"].isin(["two", "four"])]

                   A         B         C         D      E
2022-01-01 -1.200152 -2.126619 -1.314353 -0.656879    one
2022-01-02 -0.570162  0.632777  1.306604 -0.959269    one
2022-01-03  0.410459  0.026635  1.061087 -0.906371    two
2022-01-04  0.857084  1.175681 -1.448692 -0.436976  three
2022-01-05 -0.222425 -1.417048 -2.063990  0.181362   four
2022-01-06  0.202408 -0.615880  0.388940 -0.651837  three


A         B         C         D     E
2022-01-03  0.410459  0.026635  1.061087 -0.906371   two
2022-01-05 -0.222425 -1.417048 -2.063990  0.181362  four

## Setting

In [25]:
s1 = pd.Series([1, 2, 3, 4, 5, 6], index=pd.date_range("20130102", periods=6))
s1

2013-01-02    1
2013-01-03    2
2013-01-04    3
2013-01-05    4
2013-01-06    5
2013-01-07    6
Freq: D, dtype: int64

In [26]:
df["F"] = s1
df.at[dates[0], "A"] = 0
df.iat[0, 1] = 0
df.loc[:, "D"] = np.array([5] * len(df))
df

/var/folders/hx/h8g8qz553gxdl2pllvl7p69r0000gn/T/ipykernel_1520/1013604909.py:4: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[:, "D"] = np.array([5] * len(df))


A         B         C  D   F
2022-01-01  0.000000  0.000000 -1.314353  5 NaN
2022-01-02 -0.570162  0.632777  1.306604  5 NaN
2022-01-03  0.410459  0.026635  1.061087  5 NaN
2022-01-04  0.857084  1.175681 -1.448692  5 NaN
2022-01-05 -0.222425 -1.417048 -2.063990  5 NaN
2022-01-06  0.202408 -0.615880  0.388940  5 NaN

In [27]:
# Missing values
df1 = df.reindex(index=dates[0:4], columns=list(df.columns) + ["E"])
df1.loc[dates[0] : dates[1], "E"] = 1
df1

A         B         C  D   F    E
2022-01-01  0.000000  0.000000 -1.314353  5 NaN  1.0
2022-01-02 -0.570162  0.632777  1.306604  5 NaN  1.0
2022-01-03  0.410459  0.026635  1.061087  5 NaN  NaN
2022-01-04  0.857084  1.175681 -1.448692  5 NaN  NaN

In [28]:
df1.dropna(how="any")

Empty DataFrame
Columns: [A, B, C, D, F, E]
Index: []

In [29]:
df1.fillna(value=5)

A         B         C  D    F    E
2022-01-01  0.000000  0.000000 -1.314353  5  5.0  1.0
2022-01-02 -0.570162  0.632777  1.306604  5  5.0  1.0
2022-01-03  0.410459  0.026635  1.061087  5  5.0  5.0
2022-01-04  0.857084  1.175681 -1.448692  5  5.0  5.0

In [30]:
pd.isna(df1)

A      B      C      D     F      E
2022-01-01  False  False  False  False  True  False
2022-01-02  False  False  False  False  True  False
2022-01-03  False  False  False  False  True   True
2022-01-04  False  False  False  False  True   True

## Operations

In [31]:
df = pd.DataFrame(
    {
        "one": pd.Series(np.random.randn(3), index=["a", "b", "c"]),
        "two": pd.Series(np.random.randn(4), index=["a", "b", "c", "d"]),
        "three": pd.Series(np.random.randn(3), index=["b", "c", "d"]),
    }
)
df

one       two     three
a  1.940133  1.837719       NaN
b  0.361222 -1.367744  1.066051
c  0.094151  0.380514  1.082981
d       NaN  0.321840  0.296662

In [32]:
row = df.iloc[1]
row

one      0.361222
two     -1.367744
three    1.066051
Name: b, dtype: float64

In [33]:
column = df["two"]
column

a    1.837719
b   -1.367744
c    0.380514
d    0.321840
Name: two, dtype: float64

In [34]:
df.sub(row, axis="columns")

one       two     three
a  1.578911  3.205463       NaN
b  0.000000  0.000000  0.000000
c -0.267071  1.748258  0.016930
d       NaN  1.689584 -0.769389

In [35]:
df.sub(row, axis=1)

one       two     three
a  1.578911  3.205463       NaN
b  0.000000  0.000000  0.000000
c -0.267071  1.748258  0.016930
d       NaN  1.689584 -0.769389

In [36]:
df.sub(column, axis="index")

one  two     three
a  0.102413  0.0       NaN
b  1.728966  0.0  2.433795
c -0.286363  0.0  0.702467
d       NaN  0.0 -0.025178

In [37]:
df.sub(column, axis=0)

one  two     three
a  0.102413  0.0       NaN
b  1.728966  0.0  2.433795
c -0.286363  0.0  0.702467
d       NaN  0.0 -0.025178

In [38]:
# Apply lamda functions
df.apply(lambda x: x.max() - x.min())

one      1.845982
two      3.205463
three    0.786319
dtype: float64

In [39]:
# Concate
df = pd.DataFrame(np.random.randn(10, 4))
df
pieces = [df[:3], df[3:7], df[7:]]
pd.concat(pieces)

0         1         2         3
0  0.479253 -0.242368  0.120805 -1.477572
1 -1.908403  1.033414  0.997029 -1.396630
2 -0.946619  0.156048 -0.521349 -0.958363
3 -1.067484 -0.204636  1.751111 -0.534841
4 -0.304805  0.689278  0.069561  0.898056
5 -0.414748  1.109035  0.454398  1.152256
6  0.917654 -0.986476  0.399657 -1.149538
7  0.468435 -1.492677 -0.544654 -0.541346
8 -0.536298 -0.774274  1.320156  0.198224
9  1.428857 -0.174565 -0.824340  0.114781

In [40]:
# Joins
left = pd.DataFrame({"key": ["foo", "bar"], "lval": [1, 2]})
right = pd.DataFrame({"key": ["foo", "bar"], "rval": [4, 5]})
left
right
pd.merge(left, right, on="key")

key  lval  rval
0  foo     1     4
1  bar     2     5

In [41]:
# Grouping
df = pd.DataFrame(
    {
        "A": ["foo", "bar", "foo", "bar", "foo", "bar", "foo", "foo"],
        "B": ["one", "one", "two", "three", "two", "two", "one", "three"],
        "C": np.random.randn(8),
        "D": np.random.randn(8),
    }
)
df

A      B         C         D
0  foo    one -0.325668 -1.115422
1  bar    one -0.761805  1.073333
2  foo    two -1.007813 -0.286093
3  bar  three  0.304581  0.680322
4  foo    two  0.004935 -1.672458
5  bar    two  0.210756  0.134065
6  foo    one -0.676593  0.152220
7  foo  three -2.063629  0.207102

In [42]:
df.groupby("A")[["C", "D"]].sum()

C         D
A                      
bar -0.246467  1.887720
foo -4.068767 -2.714652

In [43]:
df.groupby(["A", "B"]).sum()

C         D
A   B                        
bar one   -0.761805  1.073333
    three  0.304581  0.680322
    two    0.210756  0.134065
foo one   -1.002261 -0.963202
    three -2.063629  0.207102
    two   -1.002878 -1.958551